version: "{build}"

environment:
  SNYK_TOKEN:
    secure: 8HHcJP7ARHNAWFRocNJtjNf3djhJd1IdDApO1cTnoBhW4Xr5gbfeY6GS1hAfVVI7

install:
  - dir C:\avvm\node
  - ps: $nodejs_version = Get-Content .nvmrc -Raw | foreach{ $_.Trim()}
  - ps: Install-Product node 12.16.0
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm run static
  - npm test

matrix:
  fast_finish: true
