language: node_js
branches:
  only:
  - master
env:
  global:
  - secure: O6MZLL2iFyBn85t9IFA4FPFujf3xEn4B5CJAP4aUGpDTXHrvG+5Eyj2kU7carBN38uVgb3VDJ/SoWybHfo7o+wy0jIEPEct/xmfb1vzckbLaR+62OlrLDoqTs/jlNLVeQWo46WwYdAVUIdwaCoboi98S7sdbrOs/sWmVKnNtmnlLRuT6hamZMS43KLSpZfq7n913jEZrkHFGxILki/yrnd14+0bTTy2d1PQYMawy2lj+PdmNGX+to+QBTeTtaY0WCc4INXZQt2ckNy5NMeP8UgagITwRj1sJpAv41lCuhRIQ+ZvuverfvO+ZQQ6K6TaeC2VnnlYs09fi4GOTzzJmNZe+2kWBCywy+OIle7jIjFH5hxmds1Li88MCaplBlRi7eh8rQtxrmvWT+4U/kZ7eZFHf/tdi2rGD5lSpGVEJeHf4oWdunaVlv8P7T1uWxFIDIxL6MtlJiYeINO2+9anR369kWUsr2hNmuNzY77AZrPTD+wyfZg9v+2QFclwUlW0vGKwXDlJqqH6cUx2bSZ6uByRdpUMpApoJsV2GbBM0R9Yn+jNgupNZLC5cjeClcuRORB4gy+PTUFWUUaHH4CXbxYj0GoduI9+AZPu3LfLhUOiC5VpOKeXlOWW9IGV3o6vf8Zw8nPNmLk/VFqyOY4QxtKRHbD6twAu/qMOzEKYh2Pc=
  - secure: 0dEI1QivjPDVNfew5wtuu9z2JSUOV0y1yPKqDQFrEXofKpiPgcR4fwew4HpJRum6GVOQlzFnudV9zX/f/9+RYPh2X7hT+snv0bOFJH0H86xAIRxlmg7UbjCOEyzR5LjWiSJL0EEuFskZyhuVoCjjvJg6YwMcZySW5pYpzZZlGOZ/4MUtf0Ukm9nZFK+vo0bHl5NZ78/bAqtZw9qeO7BuesoD0wQ6LmKHtVl5jCG2saRMw20wdvkENCsn3lR9mUbsBjQkO8k/bqJERCwpQb8kWsRoQ20tq+n3vWZiHsDelYW3Vfk5qQ6lDu890v2NvQa5n0x2FeR20E3qVHdbY0lBreKt9n2MF8PFxv3cxqZ0sfX8S4hbmIdPIpWDd6BTyrElatizKgVqnDL0ZCbv3iJREbWB8Gcnijy9dPcBkqru4lavTKpiQQphugaWHpgeSHcAB4XEKOOplvbtoPl/jNikvAXExTwtC8AHCwkizXXFlaJN+MTjrvT7vF/SCP2IzIFDsRYAMa80fFKSx+FZnRbMK4SHUdM6uLsEmTtYKsXNY4dUm+b52Yvcb88psAqM/UcZOr+gSuRKXTh3X5t9rSQ7QJt+U12DRTD4pAS5C+rxu6/ycWxtCVzLRNkeGdapsmmK2MALzPYDTJNiUhrdichwxFh66zvawzO+hJYBGX4u0b8=
cache:
  directories:
  - node_modules
addons:
  sauce_connect:
    username: gerbeth
  hosts:
  - travis.dev
before_install:
- sudo apt-get install libtool automake autoconf nasm
install:
- npm install --no-optional
- npm run build
before_script:
- npm run start &
- sleep 10
script:
- npx mocha
after_success:
- npm run release
- git push --follow-tags https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
