language: node_js
branches:
  only:
  - master
env:
  global:
  #github
  - secure: O6MZLL2iFyBn85t9IFA4FPFujf3xEn4B5CJAP4aUGpDTXHrvG+5Eyj2kU7carBN38uVgb3VDJ/SoWybHfo7o+wy0jIEPEct/xmfb1vzckbLaR+62OlrLDoqTs/jlNLVeQWo46WwYdAVUIdwaCoboi98S7sdbrOs/sWmVKnNtmnlLRuT6hamZMS43KLSpZfq7n913jEZrkHFGxILki/yrnd14+0bTTy2d1PQYMawy2lj+PdmNGX+to+QBTeTtaY0WCc4INXZQt2ckNy5NMeP8UgagITwRj1sJpAv41lCuhRIQ+ZvuverfvO+ZQQ6K6TaeC2VnnlYs09fi4GOTzzJmNZe+2kWBCywy+OIle7jIjFH5hxmds1Li88MCaplBlRi7eh8rQtxrmvWT+4U/kZ7eZFHf/tdi2rGD5lSpGVEJeHf4oWdunaVlv8P7T1uWxFIDIxL6MtlJiYeINO2+9anR369kWUsr2hNmuNzY77AZrPTD+wyfZg9v+2QFclwUlW0vGKwXDlJqqH6cUx2bSZ6uByRdpUMpApoJsV2GbBM0R9Yn+jNgupNZLC5cjeClcuRORB4gy+PTUFWUUaHH4CXbxYj0GoduI9+AZPu3LfLhUOiC5VpOKeXlOWW9IGV3o6vf8Zw8nPNmLk/VFqyOY4QxtKRHbD6twAu/qMOzEKYh2Pc=
  #saucelab
  - secure: VmCdViQtzKqO0JlOrf3ltKxdDl+RrlOY7UltS7IbC49LoUYvp8qn9ao/JyGjT61xNLAatlgv17QCLDywsLiLR+aFIUWd9h17oUUQ6bb0OfdhVZMfMtrPETD5L5TZP5NfrhWs0N0/d7aAmjgqn5ClhlyHYDV5EWkoSeeveFwv22jXDT5Nd2iqwlR7R57Mjog6Nz+q1BXrkE7cKixGbxgfCUuQYxXOU/hp7x5T6Wum82YBZkJicRleT1FNYSiXkZ0a9JMoomMKaVmyY6mweWbvFXYVdokEfQ4PbPCM/UMoJlQTvAHe1xpisYo4kGGjsqsKsVKs6MxXRjRSCgD30aQqrB3oyHgyZ3QO42hZO1zFmaX9oMdwbXyYCSnTWLMGruUCgyP6AjSgQ9pQ2qIZjSQ0OXC2/c0LSiBJlcJRF0pMGxkh3weyEJ0Eg9e+EXr/Qgv15fSJplsZM95F5IYmaF075aelSR/vus0zzlYnWL6CWd1xyZA3+u1hoscVkhUCkMFkg8lViwdcHHs2RT1bQgEwGObOmx/5dwHKo1JxQgK/I6PoS9ayuhMFqqHG8hANwDkumVpCIc0ItkqCoqrUGHw5CmW64kBjHw2KFKVL/rvlChLnngAizjii0tSwU3JwS2JTyhxqoIQWinIWAodx94x/ehCSbxZC04+kIY1GBYzvhBU=
cache:
  directories:
    - node_modules
addons:
  sauce_connect:
    username: gerbeth
  hosts:
    - travis.dev
before_install:
  - sudo apt-get install libtool automake autoconf nasm
install:
  - npm install --no-optional
  - npm run build
before_script:
  - npm run start & # start a Web server
  - sleep 10 # give Web server some time to bind to sockets, etc
script:
  - npx mocha
after_success:
  - npm run release
  - git push --follow-tags https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
